const targetFiles = [
  "app/static/js/audio/ws_audio_runtime.js",
  "app/static/js/audio/pcm_sender.js",
  "app/static/js/ws_client.js",
  "app/static/js/app.js",
];

export default [
  {
    files: targetFiles,
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        performance: "readonly",
        WebSocket: "readonly",
        localStorage: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        AppState: "readonly",
        WSClient: "readonly",
        VAD: "readonly",
        VoicePlayer: "readonly",
        AudioWorkletNode: "readonly",
        location: "readonly",
        alert: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        showToast: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        CustomEvent: "readonly",
        emitConsoleBusEvent: "readonly",
        sessionStorage: "readonly",
        Buffer: "readonly",
        btoa: "readonly",
        TextDecoder: "readonly",
        startRecording: "readonly",
      },
    },
    rules: {
      "no-unreachable": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-undef": "error",
      "no-unused-vars": ["error", {
        varsIgnorePattern: ".*",
        args: "after-used",
        argsIgnorePattern: ".*",
        caughtErrors: "none",
      }],
      "no-unexpected-multiline": "error",
      "no-dupe-keys": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
    },
  },
];
