"""Event constants for AskChip voice v2 telemetry."""

EVT_WS_OPEN = "EVT_WS_OPEN"
EVT_WS_CLOSE = "EVT_WS_CLOSE"
EVT_WS_JSON_RECV = "EVT_WS_JSON_RECV"
EVT_WS_JSON_SEND = "EVT_WS_JSON_SEND"
EVT_SESSION_STEP = "EVT_SESSION_STEP"
EVT_WS_AUDIO_RECV = "EVT_WS_AUDIO_RECV"
EVT_WS_AUDIO_SEND = "EVT_WS_AUDIO_SEND"
EVT_CHAT_USER = "EVT_CHAT_USER"

EVT_TTS_START = "tts.start"
EVT_TTS_END = "tts.end"
EVT_TTS_MASK = "EVT_TTS_MASK"

EVT_TURN_STATE = "EVT_TURN_STATE"
EVT_TURN_BEGIN = "EVT_TURN_BEGIN"
EVT_TURN_END = "EVT_TURN_END"
EVT_TURN_ROLLUP = "EVT_TURN_ROLLUP"
EVT_PERF_SUMMARY = "EVT_PERF_SUMMARY"

EVT_POLICY_APPLIED = "EVT_POLICY_APPLIED"
EVT_ACWR_RECOMPUTE = "EVT_ACWR_RECOMPUTE"

EVT_MIC_GATE = "EVT_MIC_GATE"
EVT_BARGE_DETECTED = "EVT_BARGE_DETECTED"
EVT_BARGE_CONFIRMED = "EVT_BARGE_CONFIRMED"
EVT_BARGE_REJECTED = "EVT_BARGE_REJECTED"
EVT_ACTION_SAY_END = "EVT_ACTION_SAY_END"

EVT_ASR_READY = "EVT_ASR_READY"
EVT_ASR_OPEN = "EVT_ASR_OPEN"
EVT_ASR_PARTIAL = "EVT_ASR_PARTIAL"
EVT_ASR_FINAL = "EVT_ASR_FINAL"
EVT_ASR_FINAL_SUPPRESSED_DUP = "EVT_ASR_FINAL_SUPPRESSED_DUP"
EVT_ASR_CLOSED = "EVT_ASR_CLOSED"
EVT_NLU = "EVT_NLU"
EVT_NLG = "EVT_NLG"
EVT_LLM_RESPONSE_START = "EVT_LLM_RESPONSE_START"
EVT_LLM_RESPONSE_END = "EVT_LLM_RESPONSE_END"
EVT_DIALOG_PLAN = "EVT_DIALOG_PLAN"
EVT_HUD_STATE = "EVT_HUD_STATE"
EVT_CLIENT_MIC_OPEN = "EVT_CLIENT_MIC_OPEN"
EVT_CLIENT_BANNER = "EVT_CLIENT_BANNER"
EVT_CLIENT_LOG = "EVT_CLIENT_LOG"
EVT_CLIENT_AUTOSTART = "EVT_CLIENT_AUTOSTART"

__all__ = [
    "EVT_WS_OPEN",
    "EVT_WS_CLOSE",
    "EVT_WS_JSON_RECV",
    "EVT_WS_JSON_SEND",
    "EVT_SESSION_STEP",
    "EVT_WS_AUDIO_RECV",
    "EVT_WS_AUDIO_SEND",
    "EVT_CHAT_USER",
    "EVT_TTS_START",
    "EVT_TTS_END",
    "EVT_TTS_MASK",
    "EVT_TURN_STATE",
    "EVT_TURN_BEGIN",
    "EVT_TURN_END",
    "EVT_TURN_ROLLUP",
    "EVT_PERF_SUMMARY",
    "EVT_POLICY_APPLIED",
    "EVT_ACWR_RECOMPUTE",
    "EVT_MIC_GATE",
    "EVT_BARGE_DETECTED",
    "EVT_BARGE_CONFIRMED",
    "EVT_BARGE_REJECTED",
    "EVT_ACTION_SAY_END",
    "EVT_ASR_READY",
    "EVT_ASR_OPEN",
    "EVT_ASR_PARTIAL",
    "EVT_ASR_FINAL",
    "EVT_ASR_FINAL_SUPPRESSED_DUP",
    "EVT_ASR_CLOSED",
    "EVT_NLU",
    "EVT_NLG",
    "EVT_LLM_RESPONSE_START",
    "EVT_LLM_RESPONSE_END",
    "EVT_DIALOG_PLAN",
    "EVT_HUD_STATE",
    "EVT_CLIENT_MIC_OPEN",
    "EVT_CLIENT_BANNER",
    "EVT_CLIENT_LOG",
    "EVT_CLIENT_AUTOSTART",
]
