"""Event constants for AskChip voice v2 telemetry."""

EVT_WS_OPEN = "EVT_WS_OPEN"
EVT_WS_CLOSE = "EVT_WS_CLOSE"
EVT_WS_JSON_RECV = "EVT_WS_JSON_RECV"
EVT_WS_JSON_SEND = "EVT_WS_JSON_SEND"
EVT_WS_AUDIO_RECV = "EVT_WS_AUDIO_RECV"
EVT_WS_AUDIO_SEND = "EVT_WS_AUDIO_SEND"
EVT_CHAT_USER = "EVT_CHAT_USER"

EVT_TTS_START = "EVT_TTS_START"
EVT_TTS_END = "EVT_TTS_END"

EVT_POLICY_APPLIED = "EVT_POLICY_APPLIED"
EVT_ACWR_RECOMPUTE = "EVT_ACWR_RECOMPUTE"

EVT_MIC_GATE = "EVT_MIC_GATE"
EVT_BARGE_IN = "EVT_BARGE_IN"

EVT_ASR_READY = "EVT_ASR_READY"
EVT_ASR_OPEN = "EVT_ASR_OPEN"
EVT_ASR_PARTIAL = "EVT_ASR_PARTIAL"
EVT_ASR_FINAL = "EVT_ASR_FINAL"
EVT_NLU = "EVT_NLU"
EVT_NLG = "EVT_NLG"
EVT_DIALOG_PLAN = "EVT_DIALOG_PLAN"
EVT_HUD_STATE = "EVT_HUD_STATE"

__all__ = [
    "EVT_WS_OPEN",
    "EVT_WS_CLOSE",
    "EVT_WS_JSON_RECV",
    "EVT_WS_JSON_SEND",
    "EVT_WS_AUDIO_RECV",
    "EVT_WS_AUDIO_SEND",
    "EVT_CHAT_USER",
    "EVT_TTS_START",
    "EVT_TTS_END",
    "EVT_POLICY_APPLIED",
    "EVT_ACWR_RECOMPUTE",
    "EVT_MIC_GATE",
    "EVT_BARGE_IN",
    "EVT_ASR_READY",
    "EVT_ASR_OPEN",
    "EVT_ASR_PARTIAL",
    "EVT_ASR_FINAL",
    "EVT_NLU",
    "EVT_NLG",
    "EVT_DIALOG_PLAN",
    "EVT_HUD_STATE",
]
