"""Shared telemetry event name constants used across the server."""
from __future__ import annotations

EVT_SESSION_TRANSPORT_CLOSED = "EVT_SESSION_TRANSPORT_CLOSED"
SESSION_TEARDOWN_COMPLETE = "SESSION_TEARDOWN_COMPLETE"

ASR_VENDOR_CONNECT_INTENT = "ASR_VENDOR_CONNECT_INTENT"
ASR_VENDOR_CLOSE_ACK = "ASR_VENDOR_CLOSE_ACK"
ASR_KEEPALIVE_PING = "ASR_KEEPALIVE_PING"
ASR_VENDOR_BYTES_TOTAL = "ASR_VENDOR_BYTES_TOTAL"
ASR_ROLLUP = "ASR_ROLLUP"
AUDIO_WIRE_ROLLUP = "AUDIO_WIRE_ROLLUP"
ASR_POST_CLOSE_DROP = "ASR_POST_CLOSE_DROP"
ASR_SINGLE_STREAM_INVARIANT = "ASR_SINGLE_STREAM_INVARIANT"

EVT_ASR_OPEN = "EVT_ASR_OPEN"
EVT_ASR_CLOSE = "EVT_ASR_CLOSE"
ASR_READY = "EVT_ASR_READY"
ASR_OPEN_QUEUED = "ASR_OPEN_QUEUED"
ASR_OPEN_DEDUP = "ASR_OPEN_DEDUP"
ASR_OPEN_AFTER_TTS = "ASR_OPEN_AFTER_TTS"

WS_AUDIO_HEADER_ACCEPT = "WS_AUDIO_HEADER_ACCEPT"
WS_AUDIO_FIRST_CHUNK = "ws.audio.first_chunk"
CLIENT_IDLE_TICK = "client.idle.tick"

__all__ = [
    "EVT_SESSION_TRANSPORT_CLOSED",
    "SESSION_TEARDOWN_COMPLETE",
    "ASR_VENDOR_CONNECT_INTENT",
    "ASR_VENDOR_CLOSE_ACK",
    "ASR_KEEPALIVE_PING",
    "ASR_VENDOR_BYTES_TOTAL",
    "ASR_ROLLUP",
    "AUDIO_WIRE_ROLLUP",
    "ASR_POST_CLOSE_DROP",
    "ASR_SINGLE_STREAM_INVARIANT",
    "EVT_ASR_OPEN",
    "EVT_ASR_CLOSE",
    "ASR_READY",
    "ASR_OPEN_QUEUED",
    "ASR_OPEN_DEDUP",
    "ASR_OPEN_AFTER_TTS",
    "WS_AUDIO_HEADER_ACCEPT",
    "WS_AUDIO_FIRST_CHUNK",
    "CLIENT_IDLE_TICK",
]
